apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
    version: "1"
spec:
  containers:
    - name: kuard
      image: "gcr.io/kuar-demo/kuard-amd64:green"
      resources:
        limits:
          memory: "58Mi"
          cpu: "100m"
      ports:
        - containerPort: 8080
