apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
        name: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: phirmware/nodeapp
          resources:
            limits:
              memory: "58Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
              name: nodeappport
        # - name: ambassador
        #   image: phirmware/ambassador
        #   resources:
        #     limits:
        #       memory: "58Mi"
        #       cpu: "100m"
        #   ports:
        #     - containerPort: 8080
        #       name: ambassadorport
        - name: nginx
          image: nginx:alpine
          resources:
            limits:
              memory: "58Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
              name: nginxport
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: experiment-config

---
kind: Service
apiVersion: v1
metadata:
  name: nodeappservice
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - name: port
      port: 80
      targetPort: nginxport
